services:
  - type: web
    name: acpn-ota-zone
    env: node
    buildCommand: |
      cd frontend && npm install && npm run build
      cd ../backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NPM_VERSION
        value: 9.6.7
      - key: VITE_API_URL
        value: https://acpn-ota-zone.onrender.com
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        sync: false
      - key: REDIS_URL
        value: redis://red-cp0c8c8l6cac73c8q0qg:6379
      - key: REDIS_PASSWORD
        sync: false
      - key: REDIS_USERNAME
        value: default
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGIN
        value: https://acpn-ota-zone.onrender.com 